# Generated by Django 3.1 on 2020-09-13 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Cat_Id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Cat_name', models.CharField(max_length=30, unique=True)),
                ('Age_group', models.PositiveIntegerField(unique=True)),
                ('Special_offers', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Myntra',
            fields=[
                ('M_Id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, unique=True)),
                ('Discount', models.SmallIntegerField(unique=True)),
                ('Cat_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Flipcart',
            fields=[
                ('F_Id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, unique=True)),
                ('Discount', models.SmallIntegerField(unique=True)),
                ('Cat_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Id', models.PositiveIntegerField(unique=True)),
                ('C_name', models.CharField(max_length=30, unique=True)),
                ('Contact', models.PositiveIntegerField(unique=True)),
                ('Address', models.TextField(unique=True)),
                ('F_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flipcart')),
                ('M_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.myntra')),
            ],
        ),
    ]
