# Generated by Django 3.1 on 2020-09-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='C_Id',
            new_name='CId',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='C_name',
            new_name='Cname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='F_Id',
            new_name='FId',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='M_Id',
            new_name='MId',
        ),
        migrations.RenameField(
            model_name='flipcart',
            old_name='F_Id',
            new_name='FId',
        ),
        migrations.RenameField(
            model_name='flipcart',
            old_name='F_name',
            new_name='Fname',
        ),
        migrations.RenameField(
            model_name='flipcart',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='myntra',
            old_name='M_Id',
            new_name='MId',
        ),
        migrations.RenameField(
            model_name='myntra',
            old_name='P_name',
            new_name='Pname',
        ),
        migrations.RenameField(
            model_name='myntra',
            old_name='price',
            new_name='Price',
        ),
    ]
